add vendor and bidOrderCenterId to Rate
depart-dlvrd/ffms-contract pull request #18
Opened 2022-05-16 15:59 UTC by GhadaSouki

2022-05-16 16:08 UTC, thi-van-luong requested changes
Nous pouvons pas faire ainsi.
Comme j'avais mentionné tantôt, il faut que ca soit des ID et non l'object au complet. En mettant l'object au complet, la réponse va devenir trop gros trop vite pour rien.

Nous allons mettre le bidOrderCenter au lieu de Enterprise. Il faudrait aussi ajouter le vendorId dans le bidOrderCenter. Il l'est déjà dans le dal-identification.yml mais pas dans identification-bff.yml

2022-05-18 18:36 UTC, thi-van-luong commented
pourquoi j'ai un conflit?

2022-05-18 18:43 UTC, thi-van-luong requested changes

2022-05-18 18:43 UTC, thi-van-luong commented on identification-bff.yml
> +    VendorsRate:
qui se sert de ca?

2022-05-18 18:43 UTC, thi-van-luong commented on dal-identification.yml
> +        bidOrderCenters:
enlever les modifications ici parce que ca ne sera pas comme ca qu'il sera storé. Nous ne recevrons pas le bidOrderCenters

2022-05-18 21:06 UTC, GhadaSouki commented on identification-bff.yml
> +    VendorsRate:
vendorsRate pour le tableau a gauche 

<img width="1104" alt="Screen Shot 2022-05-18 at 5 01 51 PM" src="https://user-images.githubusercontent.com/91617280/169155591-b94c9ba2-813f-4ae7-bf8c-c77892339d59.png">

2022-05-19 15:19 UTC, merged